name: build kernel
inputs:
  version:
    description: "kernel version"
    default: ""
  ktype:
    description: "kernel type"
    default: ""
  frag:
    description: "kernel config fragment path"
    required: true

runs:
  using: "composite"
  steps:
    - name: install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: build-essential flex bison libncurses-dev libelf-dev
          version: 2.0
    - name: parameters
      shell: bash
      run: |
        echo "version: ${{ inputs.version }}"
        echo "kernel type: ${{ inputs.ktype }}"
        echo "frag path: ${{ inputs.frag }}"
        cat ${{ inputs.frag }}
        uname -m
    - name: running script to build kernel
      shell: bash
      run: |
        ./build_kernel.sh -v ${{ inputs.version }} -t ${{ inputs.ktype }} -f ${{ inputs.frag }}
