name: Build
on:
  workflow_call:
    inputs:
      arch:
        description: "Target architecture of the kernel."
        required: true
        type: string
      os:
        description: "The os of the runner used to build the kernel."
        required: true
        type: string
      dir:
        description: "The directory containing all build config files."
        required: true
        type: string
      kimage:
        description: "The path of kernel image relative to the source root directory."
        required: true
        type: string

jobs:
  extract-configs:
    runs-on: ${{ inputs.os }}
    outputs:
      configs: ${{ steps.configs.outputs.configs }}
    steps:
    - uses: actions/checkout@v6
    - id: configs
      run: |
          result=""
          for config in ${{ inputs.dir }}/*.yml; do
            if [[ ! -z "$result" ]]; then
              result="$result,"
            fi
            result="$result\"$config\""
          done
          result="[$result]"
          echo "configs: $result"
          echo "configs=$result" >> $GITHUB_OUTPUT

  build:
    needs: extract-configs
    strategy:
      matrix:
        file: ${{ fromJson(needs.extract-configs.outputs.configs) }}
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v6
    - name: parse config file
      id: config
      env:
          CONFIG_FILE: ${{ matrix.file }}
      run: |
          python3 parse_yml.py
    - name: target names
      id: targets
      run: |
          SRC_KERNEL_VERSION=${{ steps.config.outputs.version }}
          if [[ "${{ steps.config.outputs.ktype }}" == "linux" ]]; then
            ROOT_URL="https://cdn.kernel.org/pub/linux/kernel/v$(echo $SRC_KERNEL_VERSION | cut -d"." -f1).x"
            if [[ "$SRC_KERNEL_VERSION" == *.y ]]; then
              SRC_KERNEL_VERSION=$(curl -s $ROOT_URL/ | grep -oE "${SRC_KERNEL_VERSION::-1}[0-9]+" | sort -r -V | head -n1)
            fi
            SRC_KERNEL_VERSION="linux-$SRC_KERNEL_VERSION"
          fi
          SUFFIX=$SRC_KERNEL_VERSION-${{ inputs.arch }}
          VMLINUX=vmlinux-$SUFFIX
          KIMAGE=$(basename ${{ inputs.kimage }})-$SUFFIX
          echo "vmlinux=$VMLINUX" >> $GITHUB_OUTPUT
          echo "kimage=$KIMAGE" >> $GITHUB_OUTPUT
          echo "version=$SRC_KERNEL_VERSION" >> $GITHUB_OUTPUT
          echo "suffix=$SUFFIX" >> $GITHUB_OUTPUT
    - name: restore cache
      id: cache
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.targets.outputs.vmlinux }}
          ${{ steps.targets.outputs.kimage }}
        key: ${{ steps.targets.outputs.suffix }}-${{ hashFiles(matrix.file) }}
    - name: parameters
      run: |
        echo "runner arch: $(uname -m)"
        echo "version: ${{ steps.config.outputs.version }}"
        echo "kernel type: ${{ steps.config.outputs.ktype }}"
        echo "------------------------------------"
        echo "frag path: ${{ steps.config.outputs.frag }}"
        cat ${{ steps.config.outputs.frag }}
        echo "------------------------------------"
    - name: running script to build kernel
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt update &> /dev/null && sudo apt install -y build-essential flex bison libncurses-dev libelf-dev &> /dev/null
        ./build_kernel.sh -v ${{ steps.config.outputs.version }} -t ${{ steps.config.outputs.ktype }} -j 4 -f ${{ steps.config.outputs.frag }}
        OUTPUT_DIR=${{ steps.targets.outputs.version }}
        mv $OUTPUT_DIR/vmlinux ${{ steps.targets.outputs.vmlinux }}
        mv $OUTPUT_DIR/${{ inputs.kimage }} ${{ steps.targets.outputs.kimage }}
    - name: list files to be uploaded
      run: |
        ls -la ${{ steps.targets.outputs.vmlinux }}
        ls -la ${{ steps.targets.outputs.kimage }}
    - name: upload kernel images as artifacts
      uses: actions/upload-artifact@v6
      with:
          name: kimage-artifacts-${{ steps.targets.outputs.suffix }}
          path: |
            ${{ steps.targets.outputs.vmlinux }}
            ${{ steps.targets.outputs.kimage }}
